import { PrismaClient, Severity, PatternType } from "@prisma/client";

const prisma = new PrismaClient();

const rules = [
  // Secrets & credentials
  {
    id: "hardcoded-api-key",
    category: "secrets",
    severity: Severity.CRITICAL,
    title: "Hardcoded API key in source",
    description: "An API key is hardcoded directly in source code. If this repository is ever public or shared, the key is compromised instantly.",
    patternType: PatternType.REGEX,
    pattern: { regex: "(api[_-]?key|apikey)\\s*[:=]\\s*['\"][A-Za-z0-9_\\-]{20,}['\"]" },
    languages: ["javascript", "typescript", "python"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Move the key to an environment variable: `const apiKey = process.env.API_KEY`",
  },
  {
    id: "hardcoded-secret",
    category: "secrets",
    severity: Severity.CRITICAL,
    title: "Hardcoded secret or password",
    description: "A secret, password, or token is hardcoded in source. This is a critical vulnerability — credentials in code can be extracted by anyone with repo access.",
    patternType: PatternType.REGEX,
    pattern: { regex: "(?:secret|password|passwd|auth_token)\\s*[:=]\\s*['\"](?!your[_-]|replace|example|placeholder|xxx|000|env\\.|process\\.)[^'\"]{8,}['\"]" },
    languages: ["javascript", "typescript", "python"],
    aiTools: ["copilot", "cursor"],
    fixTemplate: "Use environment variables: `const secret = process.env.SECRET`",
  },
  {
    id: "supabase-key-client",
    category: "secrets",
    severity: Severity.CRITICAL,
    title: "Supabase service role key in client bundle",
    description: "The Supabase service role key bypasses Row Level Security. Including it in client-side code exposes your entire database to any user.",
    patternType: PatternType.AST,
    pattern: { identifier: "SUPABASE_SERVICE_ROLE_KEY", context: "client" },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Service role keys must only be used in server-side API routes, never in components or client code.",
  },
  {
    id: "env-in-client",
    category: "secrets",
    severity: Severity.HIGH,
    title: "Server environment variable exposed in client-side code",
    description: "process.env variables without the NEXT_PUBLIC_ prefix are server-only. Using them in client components leaks them to the browser bundle.",
    patternType: PatternType.AST,
    pattern: { call: "process.env", context: "client-component" },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Prefix public variables with NEXT_PUBLIC_ or move the logic to a server component / API route.",
  },
  {
    id: "dotenv-committed",
    category: "secrets",
    severity: Severity.HIGH,
    title: ".env file committed to repository",
    description: "A .env file is present in the repository without a corresponding .gitignore entry. This exposes all secrets to anyone with repo access.",
    patternType: PatternType.FILE,
    pattern: { filenames: [".env", ".env.local", ".env.production", ".env.development"] },
    languages: ["*"],
    aiTools: ["claude-code", "cursor"],
    fixTemplate: "Add .env* to .gitignore immediately. Rotate all compromised credentials.",
  },

  // Authentication & authorisation
  {
    id: "missing-auth-api",
    category: "auth",
    severity: Severity.CRITICAL,
    title: "API route without authentication check",
    description: "This API route handler has no authentication check. Any unauthenticated user can call this endpoint, potentially accessing or modifying protected data.",
    patternType: PatternType.AST,
    pattern: { node: "ExportedFunction", missing: ["getServerSession", "auth()", "getUser", "currentUser"] },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Add auth check at the top of the handler: `const session = await auth(); if (!session) return new Response('Unauthorized', { status: 401 });`",
  },
  {
    id: "missing-rls",
    category: "auth",
    severity: Severity.HIGH,
    title: "Supabase query without RLS context",
    description: "A Supabase query is made using the service role or without proper RLS context, potentially exposing data across tenant boundaries.",
    patternType: PatternType.AST,
    pattern: { call: "supabase.from", context: "server", missingAuth: true },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Use the authenticated Supabase client: `const supabase = createServerClient(...)` with proper cookie forwarding.",
  },
  {
    id: "jwt-no-verify",
    category: "auth",
    severity: Severity.CRITICAL,
    title: "JWT decoded without verification",
    description: "jwt.decode() does not verify the token signature — it only base64-decodes the payload. An attacker can craft any payload and it will be trusted.",
    patternType: PatternType.AST,
    pattern: { call: "jwt.decode", missingPair: "jwt.verify" },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor"],
    fixTemplate: "Replace jwt.decode() with jwt.verify(token, secret) which validates the signature.",
  },
  {
    id: "no-csrf",
    category: "auth",
    severity: Severity.MEDIUM,
    title: "Form POST without CSRF protection",
    description: "A form submits via POST without CSRF token validation. This allows cross-site request forgery attacks where malicious sites trigger actions on behalf of authenticated users.",
    patternType: PatternType.AST,
    pattern: { node: "form", method: "POST", missing: "csrf" },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Add CSRF protection using a library like csrf-csrf or use Next.js Server Actions which have built-in CSRF protection.",
  },
  {
    id: "default-admin",
    category: "auth",
    severity: Severity.CRITICAL,
    title: "Default admin credentials",
    description: "Default or hardcoded admin credentials are present. These are the first thing attackers try.",
    patternType: PatternType.REGEX,
    pattern: { regex: "password\\s*[:=]\\s*['\"](?:admin|password|pass|123456|admin123|test|default|root|1234|qwerty|letmein|welcome|changeme)['\"]|DEFAULT_ADMIN_PASS(?:WORD)?\\s*=\\s*['\"][^'\"]+['\"]" },
    languages: ["javascript", "typescript", "python"],
    aiTools: ["copilot"],
    fixTemplate: "Remove all default credentials. Require secure passwords during setup.",
  },

  // Injection
  {
    id: "sql-interpolation",
    category: "injection",
    severity: Severity.CRITICAL,
    title: "SQL query with string interpolation",
    description: "User-controlled input is interpolated directly into a SQL query. This is a textbook SQL injection vulnerability allowing an attacker to read, modify, or delete any data.",
    patternType: PatternType.AST,
    pattern: { call: ["query", "raw", "execute"], argType: "TemplateLiteral" },
    languages: ["javascript", "typescript", "python"],
    aiTools: ["copilot", "cursor"],
    fixTemplate: "Use parameterised queries: `db.query('SELECT * FROM users WHERE id = $1', [userId])`",
  },
  {
    id: "nosql-injection",
    category: "injection",
    severity: Severity.HIGH,
    title: "NoSQL query with unsanitised input",
    description: "Request body or query params are passed directly to a MongoDB query. An attacker can inject query operators ($where, $gt) to bypass filters or dump data.",
    patternType: PatternType.AST,
    pattern: { call: ["find", "findOne", "updateOne", "deleteOne"], argSource: ["req.body", "req.query"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot"],
    fixTemplate: "Validate and sanitise inputs with zod before passing to MongoDB. Never spread req.body directly into a query.",
  },
  {
    id: "xss-dangerously",
    category: "injection",
    severity: Severity.HIGH,
    title: "dangerouslySetInnerHTML with user-controlled input",
    description: "dangerouslySetInnerHTML bypasses React's XSS protection. If the value is user-controlled, an attacker can inject arbitrary scripts.",
    patternType: PatternType.AST,
    pattern: { prop: "dangerouslySetInnerHTML", valueSource: ["props", "state", "api"] },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Use DOMPurify to sanitise HTML before rendering, or refactor to avoid dangerouslySetInnerHTML entirely.",
  },
  {
    id: "eval-usage",
    category: "injection",
    severity: Severity.HIGH,
    title: "eval() or Function() with dynamic input",
    description: "eval() executes arbitrary code. Any user-controlled input passed to eval() is a remote code execution vulnerability.",
    patternType: PatternType.AST,
    pattern: { call: ["eval", "new Function", "setTimeout"], argType: "dynamic" },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot"],
    fixTemplate: "Never use eval(). Use JSON.parse() for data, or refactor logic to avoid dynamic code execution.",
  },
  {
    id: "command-injection",
    category: "injection",
    severity: Severity.CRITICAL,
    title: "Shell command with unsanitised input",
    description: "User input is passed to a shell command via exec/spawn/execSync. An attacker can inject shell metacharacters to run arbitrary commands on the server.",
    patternType: PatternType.AST,
    pattern: { call: ["exec", "execSync", "spawn", "spawnSync"], argType: "TemplateLiteral" },
    languages: ["javascript", "typescript"],
    aiTools: ["claude-code"],
    fixTemplate: "Use spawn() with an args array (never shell: true), or use a library that avoids shell invocation entirely.",
  },

  // CORS & headers
  {
    id: "cors-wildcard",
    category: "cors",
    severity: Severity.HIGH,
    title: "CORS allows all origins",
    description: "Access-Control-Allow-Origin: * permits any website to make cross-origin requests to your API, enabling CSRF-style attacks on authenticated endpoints.",
    patternType: PatternType.REGEX,
    pattern: { regex: "Access-Control-Allow-Origin.*\\*|cors\\(\\s*\\{\\s*origin:\\s*true" },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Set an allowlist: `cors({ origin: ['https://yourdomain.com'] })`",
  },
  {
    id: "cors-credentials-wildcard",
    category: "cors",
    severity: Severity.CRITICAL,
    title: "CORS with credentials and wildcard origin",
    description: "Combining credentials:true with a wildcard origin is rejected by browsers but misconfigurations here can still enable session hijacking in some setups.",
    patternType: PatternType.AST,
    pattern: { corsConfig: { credentials: true, origin: ["*", "true"] } },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor"],
    fixTemplate: "When using credentials:true, you must specify an explicit origin, never a wildcard.",
  },
  {
    id: "missing-security-headers",
    category: "cors",
    severity: Severity.MEDIUM,
    title: "Missing security headers",
    description: "Security headers like X-Content-Type-Options, X-Frame-Options, and Strict-Transport-Security are absent, leaving the app vulnerable to MIME sniffing, clickjacking, and protocol downgrade attacks.",
    patternType: PatternType.FILE,
    pattern: { file: "next.config.*", missing: ["X-Content-Type-Options", "X-Frame-Options", "Strict-Transport-Security"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Add security headers to next.config.ts headers() or a middleware.ts file.",
  },
  {
    id: "no-rate-limit",
    category: "cors",
    severity: Severity.MEDIUM,
    title: "API routes without rate limiting",
    description: "No rate limiting on this API route means it can be brute-forced or abused for denial of service.",
    patternType: PatternType.AST,
    pattern: { node: "RouteHandler", missing: ["rateLimit", "rateLimiter", "upstash"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Add rate limiting using Upstash Redis or the `rate-limiter-flexible` package.",
  },

  // Data exposure
  {
    id: "full-error-client",
    category: "data-exposure",
    severity: Severity.HIGH,
    title: "Full error stack trace sent to client",
    description: "Sending error.stack or error.message directly to the client reveals implementation details (file paths, library versions, database schema) that help attackers craft targeted attacks.",
    patternType: PatternType.AST,
    pattern: { node: "catch", responseContains: ["error.stack", "error.message", "e.stack"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Log errors server-side, return only a generic message: `return NextResponse.json({ error: 'Internal server error' }, { status: 500 })`",
  },
  {
    id: "console-log-sensitive",
    category: "data-exposure",
    severity: Severity.MEDIUM,
    title: "console.log with sensitive variable",
    description: "Logging sensitive data (passwords, tokens, keys) can expose it in server logs, browser consoles, or observability tools.",
    patternType: PatternType.AST,
    pattern: { call: "console.log", argContains: ["password", "token", "secret", "key", "credential", "apiKey"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "claude-code"],
    fixTemplate: "Remove the log statement, or redact sensitive fields before logging.",
  },
  {
    id: "unfiltered-query",
    category: "data-exposure",
    severity: Severity.MEDIUM,
    title: "Database results returned without field filtering",
    description: "SELECT * followed by a direct API response exposes all columns including internal fields, hashed passwords, or soft-deleted records.",
    patternType: PatternType.AST,
    pattern: { call: "select('*')", directResponse: true },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Explicitly select only the fields you need, or use a serialiser to strip sensitive fields before returning.",
  },
  {
    id: "debug-mode-prod",
    category: "data-exposure",
    severity: Severity.HIGH,
    title: "Debug mode enabled in production config",
    description: "Debug mode in production can expose stack traces, query plans, or internal state to end users.",
    patternType: PatternType.REGEX,
    pattern: { regex: "DEBUG\\s*=\\s*true|debug:\\s*true" },
    languages: ["javascript", "typescript", "python"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Gate debug mode behind NODE_ENV checks: `debug: process.env.NODE_ENV === 'development'`",
  },

  // Dependency & config
  {
    id: "no-input-validation",
    category: "config",
    severity: Severity.HIGH,
    title: "API endpoint without input validation",
    description: "Request body or query params are used without schema validation. This can lead to type confusion, unexpected behaviour, or injection vulnerabilities.",
    patternType: PatternType.AST,
    pattern: { argSource: ["req.body", "req.query", "request.json()"], missingValidation: true },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "lovable", "bolt", "claude-code"],
    fixTemplate: "Validate all inputs with zod: `const body = RequestSchema.parse(await request.json())`",
  },
  {
    id: "unvalidated-redirect",
    category: "config",
    severity: Severity.HIGH,
    title: "Redirect using user-supplied URL",
    description: "Redirecting to a user-controlled URL enables open redirect attacks, which are used to phish users or bypass security filters.",
    patternType: PatternType.AST,
    pattern: { call: ["redirect", "router.push", "Response.redirect"], argSource: ["searchParams", "req.query", "req.body"] },
    languages: ["javascript", "typescript"],
    aiTools: ["lovable", "bolt"],
    fixTemplate: "Validate the redirect URL against an allowlist of trusted domains before redirecting.",
  },
  {
    id: "insecure-cookie",
    category: "config",
    severity: Severity.MEDIUM,
    title: "Cookie set without secure flags",
    description: "Cookies without httpOnly, secure, and sameSite flags can be read by JavaScript (XSS theft), sent over HTTP (interception), or included in cross-site requests (CSRF).",
    patternType: PatternType.AST,
    pattern: { call: ["setCookie", "cookies().set", "res.cookie"], missingFlags: ["httpOnly", "secure", "sameSite"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot"],
    fixTemplate: "Set all three flags: `cookies().set('name', value, { httpOnly: true, secure: true, sameSite: 'lax' })`",
  },

  // ── New gap rules ──────────────────────────────────────────────────────────

  {
    id: "insecure-randomness",
    category: "auth",
    severity: Severity.HIGH,
    title: "Math.random() used for security-sensitive token generation",
    description: "Math.random() is a pseudo-random number generator — it is not cryptographically secure and its output can be predicted or reconstructed. Using it for tokens, OTPs, session IDs, or password reset codes means those values can be brute-forced or predicted. Always use crypto.randomBytes() for anything security-sensitive.",
    patternType: PatternType.AST,
    pattern: { call: "Math.random", context: "token-generation" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Replace with: `const token = crypto.randomBytes(32).toString('hex');`\nOr for shorter codes: `const code = crypto.randomInt(100000, 999999).toString();`",
  },
  {
    id: "auth-callbackurl-redirect",
    category: "auth",
    severity: Severity.HIGH,
    title: "Post-auth redirect destination taken from callbackUrl without origin validation",
    description: "The redirect destination after login is read from the callbackUrl or redirectTo query parameter without validating that it points to the same origin. An attacker sends a crafted login link (e.g. /login?callbackUrl=https://evil.com) and the user is redirected to a phishing site after authenticating. This is one of the most common vulnerabilities in AI-generated auth flows.",
    patternType: PatternType.AST,
    pattern: { call: "redirect", argSource: "callbackUrl" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Validate the redirect URL before using it:\nconst safeUrl = callbackUrl?.startsWith('/') ? callbackUrl : '/dashboard';\nredirect(safeUrl);",
  },
  {
    id: "timing-attack",
    category: "auth",
    severity: Severity.MEDIUM,
    title: "Security-sensitive string compared with === (timing oracle)",
    description: "Comparing tokens, signatures, or HMAC values with === is vulnerable to timing attacks. === returns false immediately when the first character differs — an attacker can measure response time to learn how many characters of their guess are correct, eventually reconstructing the secret byte by byte. Use crypto.timingSafeEqual() instead.",
    patternType: PatternType.AST,
    pattern: { node: "BinaryExpression", operator: "===", operandContains: ["token", "signature", "hmac"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot"],
    fixTemplate: "Use constant-time comparison:\nimport { timingSafeEqual } from 'crypto';\nconst safe = timingSafeEqual(Buffer.from(received), Buffer.from(expected));",
  },
  {
    id: "ssrf",
    category: "injection",
    severity: Severity.HIGH,
    title: "Server-Side Request Forgery: fetch() called with user-controlled URL",
    description: "A server-side fetch() is called with a URL that comes from user-controlled input (request body, query params, etc.). An attacker can point the server at internal services — AWS metadata API (169.254.169.254), internal databases, Redis, or other microservices — that are not reachable from the internet but are accessible from the server itself.",
    patternType: PatternType.AST,
    pattern: { call: "fetch", argSource: ["req.body", "req.query", "searchParams"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Validate the URL against an allowlist of permitted hosts before fetching:\nconst ALLOWED_HOSTS = ['api.example.com', 'cdn.example.com'];\nconst url = new URL(userUrl);\nif (!ALLOWED_HOSTS.includes(url.hostname)) throw new Error('Forbidden host');",
  },
  {
    id: "path-traversal",
    category: "injection",
    severity: Severity.HIGH,
    title: "Path traversal: file system operation with user-controlled path",
    description: "A file system operation (readFile, writeFile, createReadStream, path.join) uses a path component that comes from user input. path.join() does NOT prevent directory traversal — path.join('/uploads', '../../etc/passwd') resolves to '/etc/passwd'. An attacker can read or overwrite arbitrary files on the server.",
    patternType: PatternType.AST,
    pattern: { call: ["fs.readFile", "path.join"], argSource: ["req.params", "req.query"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0"],
    fixTemplate: "Validate the resolved path stays within the intended directory:\nconst full = path.resolve(UPLOAD_DIR, filename);\nif (!full.startsWith(UPLOAD_DIR)) throw new Error('Path traversal attempt');",
  },
  {
    id: "nextpublic-secret",
    category: "secrets",
    severity: Severity.CRITICAL,
    title: "Server-only secret prefixed with NEXT_PUBLIC_",
    description: "The NEXT_PUBLIC_ prefix causes Next.js to inline the variable's value into the client JavaScript bundle at build time — it becomes part of every user's browser-downloaded code. Variables whose names suggest they are secrets (SECRET, PRIVATE, SERVICE_ROLE, DATABASE_URL, etc.) must never use this prefix.",
    patternType: PatternType.AST,
    pattern: { identifier: "NEXT_PUBLIC_SECRET|NEXT_PUBLIC_PRIVATE|NEXT_PUBLIC_DATABASE", context: "env" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Remove the NEXT_PUBLIC_ prefix and access the variable only in server components, API routes, or server actions.",
  },
  {
    id: "localstorage-auth-token",
    category: "auth",
    severity: Severity.HIGH,
    title: "Auth token stored in localStorage (XSS-accessible)",
    description: "Authentication tokens stored in localStorage are readable by any JavaScript running on the page. A single XSS vulnerability anywhere on the site instantly becomes an account takeover — the attacker's script reads the token and exfiltrates it. Store auth tokens in httpOnly cookies so JavaScript cannot access them.",
    patternType: PatternType.AST,
    pattern: { call: "localStorage.setItem", argContains: ["token", "jwt", "auth"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Store session tokens in httpOnly, secure, sameSite cookies instead of localStorage. Use NextAuth or a similar library that handles this automatically.",
  },
  {
    id: "missing-cache-control",
    category: "data-exposure",
    severity: Severity.MEDIUM,
    title: "User-specific API response missing Cache-Control: no-store",
    description: "This API route returns user-specific data without setting Cache-Control: no-store. Shared caches (CDN, reverse proxy, or browser shared cache) can serve one user's response to another user. Any personally identifiable data, financial records, or session-linked content must be marked as non-cacheable.",
    patternType: PatternType.AST,
    pattern: { node: "RouteHandler", hasUserQuery: true, missingHeader: "Cache-Control" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Add cache control headers to user-specific responses:\nreturn NextResponse.json(data, {\n  headers: { 'Cache-Control': 'no-store, private' },\n});",
  },
  {
    id: "email-header-injection",
    category: "injection",
    severity: Severity.HIGH,
    title: "Email header injection via user-controlled to/from/subject fields",
    description: "Email headers (to, from, cc, subject) are populated directly from request body fields without sanitisation. An attacker can inject \\r\\n sequences to add arbitrary headers — turning your mailer into a spam relay, sending emails to additional recipients, or overriding the sender address. All user-supplied email fields must be sanitised to remove newline characters.",
    patternType: PatternType.AST,
    pattern: { call: ["nodemailer.sendMail", "resend.emails.send"], argSource: ["req.body", "body"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable"],
    fixTemplate: "Sanitise all user-controlled email fields:\nconst sanitize = (s: string) => s.replace(/[\\r\\n]/g, '');\nto: sanitize(body.email), subject: sanitize(body.subject)",
  },
  {
    id: "file-upload-no-validation",
    category: "config",
    severity: Severity.HIGH,
    title: "File upload without MIME type or size validation",
    description: "A multipart form data handler accepts file uploads without checking the file type or size. Attackers can upload executables (.exe, .sh), polyglot files (SVG with embedded JavaScript), or multi-gigabyte files to crash the server. Always validate the MIME type from the file's magic bytes (not the client-supplied Content-Type) and enforce a size limit.",
    patternType: PatternType.AST,
    pattern: { call: "request.formData", missingValidation: ["type", "size", "mimetype"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Validate file type and size before processing:\nconst file = formData.get('file') as File;\nconst ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp'];\nif (!ALLOWED_TYPES.includes(file.type)) return error(400, 'Invalid file type');\nif (file.size > 5 * 1024 * 1024) return error(400, 'File too large (max 5 MB)');",
  },
  {
    id: "redos-regexp",
    category: "injection",
    severity: Severity.MEDIUM,
    title: "Regular Expression Denial of Service: new RegExp() with user input",
    description: "A regular expression is constructed using new RegExp() with a value that comes from user input. An attacker can supply a carefully crafted string that causes catastrophic backtracking in the regex engine, blocking the Node.js event loop for seconds or minutes — a Denial of Service attack with a single HTTP request.",
    patternType: PatternType.AST,
    pattern: { call: "new RegExp", argSource: ["req.body", "req.query", "searchParams"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot"],
    fixTemplate: "Never build regex from user input. Use string methods (includes, startsWith, split) instead. If you need regex, use a safe library like 're2' which prevents catastrophic backtracking.",
  },
  {
    id: "queryraw-string-concat",
    category: "injection",
    severity: Severity.CRITICAL,
    title: "Prisma $queryRaw / $executeRaw with unsafe string interpolation",
    description: "prisma.$queryRaw() is called as a function with a template literal argument instead of using it as a tagged template. The safe form `prisma.$queryRaw\\`SELECT * WHERE id = ${id}\\`` lets Prisma parameterise the query. The unsafe call form `prisma.$queryRaw(\\`SELECT * WHERE id = ${id}\\`)` does NOT — it passes the interpolated string directly, creating a SQL injection vulnerability.",
    patternType: PatternType.AST,
    pattern: { call: "prisma.$queryRaw", argType: "TemplateLiteralCallForm" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot"],
    fixTemplate: "Use $queryRaw as a tagged template (without parentheses around the template):\n// SAFE: prisma.$queryRaw`SELECT * FROM users WHERE id = ${id}`\n// UNSAFE: prisma.$queryRaw(`SELECT * FROM users WHERE id = ${id}`)",
  },
  {
    id: "sensitive-in-query-param",
    category: "data-exposure",
    severity: Severity.MEDIUM,
    title: "Security-sensitive value passed as URL query parameter",
    description: "Tokens, secrets, or API keys passed as URL query parameters appear in server access logs, browser history, Referer headers sent to linked third-party sites, and any analytics or monitoring tools. Once a reset token or session token is in a URL it should be treated as compromised. Pass sensitive values in the request body or HTTP headers instead.",
    patternType: PatternType.AST,
    pattern: { node: "URLParam", paramName: ["token", "secret", "password", "apiKey"] },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Pass sensitive values in the Authorization header or POST body instead of query params:\n// Instead of: /reset?token=abc123\n// Use: POST /reset with { token: 'abc123' } in body",
  },
  {
    id: "missing-samesite-cookie",
    category: "config",
    severity: Severity.MEDIUM,
    title: "Cookie set without sameSite attribute",
    description: "A cookie is set without the sameSite attribute. Without sameSite: 'lax' or 'strict', the cookie is sent by the browser on all cross-origin requests — including those triggered by third-party sites. This enables CSRF attacks even when using modern browsers, because cross-site navigation and form submissions carry the cookie automatically.",
    patternType: PatternType.AST,
    pattern: { call: "cookies().set", missingFlags: ["sameSite"] },
    languages: ["javascript", "typescript"],
    aiTools: ["copilot", "cursor", "v0"],
    fixTemplate: "Add sameSite to all cookie options:\ncookies().set('session', token, {\n  httpOnly: true,\n  secure: true,\n  sameSite: 'lax',  // or 'strict' for high-security contexts\n  path: '/',\n});",
  },
  {
    id: "webhook-no-verify",
    category: "auth",
    severity: Severity.CRITICAL,
    title: "Webhook handler processes payload without signature verification",
    description: "This webhook route parses the request body but does not verify the webhook signature. Anyone on the internet can POST a fake event to this endpoint — faking a Stripe payment_intent.succeeded event to grant a subscription, a GitHub push event to trigger a deployment, or a Clerk user.created event to provision admin accounts. Always verify the signature using the provider's SDK before processing.",
    patternType: PatternType.AST,
    pattern: { node: "RouteHandler", path: "webhook", missingCall: "constructEvent|verify" },
    languages: ["javascript", "typescript"],
    aiTools: ["cursor", "copilot", "v0", "bolt", "lovable", "replit"],
    fixTemplate: "Verify the webhook signature before processing:\n// Stripe:\nconst event = stripe.webhooks.constructEvent(rawBody, sig, process.env.STRIPE_WEBHOOK_SECRET);\n// GitHub:\nconst sig = req.headers.get('x-hub-signature-256');\nawait verifyGitHubWebhook(rawBody, sig, process.env.GITHUB_WEBHOOK_SECRET);",
  },
];

async function main() {
  console.log("Seeding rules...");

  for (const rule of rules) {
    await prisma.rule.upsert({
      where: { id: rule.id },
      update: rule,
      create: rule,
    });
  }

  console.log(`✓ Seeded ${rules.length} rules`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
